apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: otel-collector-pod-reader
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces", "nodes", "services", "endpoints"]
    verbs: ["get", "list", "watch"]
