apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-collector-nephio-config-management # kpt-set: ${configMapName}
  namespace: monitoring # kpt-set: ${namespace}
data:
  config.yaml: |-
    receivers:
      otlp:
        protocols:
          grpc:
          http:

      filelog:
        include:
          - /var/log/pods/porch-system_porch-server-*/porch-server/*.log
          - /var/log/pods/porch-system_porch-controllers-*/porch-controllers/*.log
        start_at: beginning
        include_file_name: false
        include_file_path: true
        operators:
          - type: regex_parser
            id: parse_k8s_log
            regex: '^(?P<k8s_timestamp>[^ ]+) (?P<stream>stdout|stderr) (?P<flag>\S+) (?P<level>[A-Z])(?P<log_timestamp>\d{4} \d{2}:\d{2}:\d{2}\.\d+) +(?P<thread>\d+) (?P<location>\S+):(?P<line>\d+)] (?P<msg>.+)$'
            timestamp:
              parse_from: attributes.k8s_timestamp
              layout: '%Y-%m-%dT%H:%M:%S.%fZ'
            severity:
              parse_from: attributes.level
              mapping:
                I: info
                W: warn
                E: error
                F: fatal

    processors:
      batch:
        send_batch_size: 1000
        timeout: 10s
        send_batch_max_size: 10000

    exporters:
      debug:
        verbosity: detailed

      elasticsearch:
        endpoints: ["https://${ELASTIC_HOST}:${ELASTIC_PORT}"]  # Set ELASTIC_HOST and ELASTIC_PORT
        user: "elastic"
        password: "${ELASTIC_PASSWORD}"  # Set this in a Kubernetes Secret and mount it as env var
        tls:
          insecure_skip_verify: true  # only use for testing; configure TLS properly in prod
        logs_dynamic_index:
          enabled: true

    service:
      telemetry:
        logs:
          level: debug
          encoding: console
      pipelines:
        logs:
          receivers: [filelog]
          processors: [batch]
          exporters: [elasticsearch]
